#   Generations
MAX_GENERATIONS = 10

# Tree Generation
POPULATION_SIZE = 20
INITIAL_TREE_DEPTH = 6
TREE_GENERATION_METHOD = "RAMPED"

RANDOM_STATE = 42

SEED = 21

# Tournament Selection
TOURNAMENT_SIZE = int(0.2 * POPULATION_SIZE)

#   operators.py
CROSSOVER_RATE = 0.7
MUTATION_RATE = 0.3
MAX_TREE_DEPTH = 8

#   fitness.py
FITNESS_FUNCTION = 'MedAE'
