# Tree Generation
POPULATION_SIZE = 5
INITIAL_TREE_DEPTH = 6
TREE_GENERATION_METHOD = "RAMPED"

RANDOM_STATE = 42

SEED = 21

# Tournament Selection
TOURNAMENT_SIZE = 5

#   operators.py
CROSSOVER_RATE = 0.8
MUTATION_RATE = 0.4
MAX_TREE_DEPTH = 8

#   fitness.py
FITNESS_FUNCTION = 'MedAE'
